# -*- coding: utf-8 -*-
"""innovation_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5OuBMySVo9tEWSEUPcaUkX-8612uLlI
"""

!pip install diffusers transformers accelerate torch gradio

from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5"
).to("cuda")

"""## Generate Images with Stable Diffusion

First, let's define a function that takes a text prompt and generates an image using our `StableDiffusionPipeline`.
"""

import io
from PIL import Image

def generate_manufacturing_image(prompt):
    """Generates an image based on a text prompt using the pre-trained Stable Diffusion pipeline."""
    # Generate image
    image = pipe(prompt).images[0]
    return image

"""## Build a Gradio Interface

Now, let's create a user-friendly Gradio interface for your data scientists and engineers to input prompts and generate images. We'll include some example manufacturing-related prompts.
"""



import torch
torch.cuda.is_available()

from diffusers import StableDiffusionPipeline
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5"
).to(device)



from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5"
).to("cuda")

image = pipe("metal crack defect industrial surface").images[0]
image

import gradio as gr

def generate(process, defect):
    prompt = f"close-up of metal surface after {process} showing {defect} defect, industrial inspection, no humans, high detail"
    image = pipe(prompt).images[0]
    return image

demo = gr.Interface(
    fn=generate,
    inputs=[
        gr.Dropdown(["welding", "casting","molding","forming","machining","joining","additive manufacturing","cutting","punching","forging","extrusion"], label="Select Process"),
        gr.Dropdown(["crack", "porosity","crater","spatter","lamellar tearing","distortion","misallignment","whiskers"], label="Select Defect")
    ],
    outputs="image",
    title="AI Manufacturing Defect Generator",
    description="Generate realistic defect images using AI"
)

demo.launch()

